// This file is automatically generated by `pnpm --filter @geographer/studio typegen`.
// It will be overwritten on each type generation run.
// The definitions below are placeholders to keep TypeScript happy before the
// generator runs. Do not edit them manually outside of the generator workflow.

export type HOMEPAGE_QUERYResult = {
  title?: string | null;
  videos?: Array<
    | {
        _id?: string;
        _key?: string;
        asset?: { _ref?: string; playbackId?: string | null };
      }
    | null
  > | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: { alt?: string | null } | null;
  } | null;
} | null;

export type ABOUT_QUERYResult = {
  richText?: unknown;
  image?: { alt?: string | null } | null;
  imageText?: unknown;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: { alt?: string | null } | null;
  } | null;
} | null;

export type SITE_SETTINGS_QUERYResult = {
  mainMenu?: Array<
    | {
        _key?: string;
        label?: string | null;
        linkType?: string | null;
        externalLink?: string | null;
        internalLink?: {
          slug?: { current?: string | null } | null;
        } | null;
      }
    | null
  > | null;
  footerMenu?: Array<
    | {
        _key?: string;
        label?: string | null;
        linkType?: string | null;
        externalLink?: string | null;
        internalLink?: {
          slug?: { current?: string | null } | null;
        } | null;
      }
    | null
  > | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  } | null;
} | null;

export type RELEASE_SLUGS_QUERYResult = Array<{ slug?: string | null } | null> | null;

export type RELEASES_QUERYResult = Array<{
  _id?: string;
  title?: string | null;
  slug?: { current?: string | null } | null;
  release_date?: string | null;
}> | null;

export type RELEASE_BY_SLUG_QUERYResult = {
  _id?: string;
  title?: string | null;
  slug?: { current?: string | null } | null;
  release_date?: string | null;
  intro?: string | null;
  quote?: string | null;
  embed?: string | null;
} | null;

export type COLLECTION_SLUGS_QUERYResult = Array<{ slug?: string | null } | null> | null;

export type COLLECTIONS_QUERYResult = Array<{
  _id?: string;
  title?: string | null;
  slug?: { current?: string | null } | null;
  location?: string | null;
  dates?: string | null;
  partners?: string | null;
}> | null;

export type COLLECTION_BY_SLUG_QUERYResult = {
  _id?: string;
  title?: string | null;
  slug?: { current?: string | null } | null;
  location?: string | null;
  dates?: string | null;
  partners?: string | null;
  intro?: unknown;
  releases?: Array<
    | {
        _id?: string;
        title?: string | null;
        slug?: { current?: string | null } | null;
      }
    | null
  > | null;
  press?: Array<
    | {
        title?: string | null;
        externalLink?: string | null;
        file?: { asset?: { url?: string | null } | null } | null;
      }
    | null
  > | null;
} | null;

export type PROJECT_SLUGS_QUERYResult = Array<{ slug?: string | null } | null> | null;

export type PROJECTS_QUERYResult = Array<{
  _id?: string;
  title?: string | null;
  slug?: { current?: string | null } | null;
  location?: string | null;
  dates?: string | null;
  partners?: string | null;
}> | null;

export type PROJECT_BY_SLUG_QUERYResult = {
  _id?: string;
  title?: string | null;
  slug?: { current?: string | null } | null;
  location?: string | null;
  dates?: string | null;
  partners?: string | null;
  columns?: Array<unknown> | null;
  gallery?: Array<
    | {
        _id?: string;
        _key?: string;
        alt?: string | null;
      }
    | null
  > | null;
  images?: Array<
    | {
        _id?: string;
        _key?: string;
        alt?: string | null;
      }
    | null
  > | null;
  press?: Array<
    | {
        title?: string | null;
        externalLink?: string | null;
        file?: { asset?: { url?: string | null } | null } | null;
      }
    | null
  > | null;
} | null;

