/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PressItem = {
  _type: "pressItem";
  title?: string;
  externalLink?: string;
  file?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
};

export type MenuItem = {
  _type: "menuItem";
  label?: string;
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "about";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homepage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "release";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "collection";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "project";
  };
  externalLink?: string;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "externalLink";
    _key: string;
  } | {
    reference?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "about";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "homepage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "release";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "collection";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "project";
    };
    _type: "internalLink";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "richImage";
  _key: string;
}>;

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainMenu?: Array<{
    _key: string;
  } & MenuItem>;
  footerMenu?: Array<{
    _key: string;
  } & MenuItem>;
  seo?: Seo;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  richText?: RichText;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "richImage";
  };
  imageText?: RichText;
  seo?: Seo;
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  hero?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "richImage";
  };
  lines?: Array<{
    label?: string;
    value?: string;
    link?: string;
    _type: "line";
    _key: string;
  }>;
  intro?: RichText;
  releases?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "release";
  }>;
  press?: Array<{
    _key: string;
  } & PressItem>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  lines?: Array<{
    label?: string;
    value?: string;
    link?: string;
    _type: "line";
    _key: string;
  }>;
  columns?: Array<{
    content?: RichText;
    _type: "column";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "richImage";
    _key: string;
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "richImage";
    _key: string;
  }>;
  press?: Array<{
    _key: string;
  } & PressItem>;
};

export type Release = {
  _id: string;
  _type: "release";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  published?: boolean;
  release_date?: string;
  cover?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "richImage";
  };
  coverAlt?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "richImage";
  };
  intro?: string;
  embed?: string;
  quote?: string;
};

export type RichImage = {
  _type: "richImage";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  videos?: Array<{
    _key: string;
  } & MuxVideo>;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: RichImage;
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "mux.videoAsset";
  };
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<{
    _key: string;
  } & MuxTrack>;
  playback_ids?: Array<{
    _key: string;
  } & MuxPlaybackId>;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<{
    _key: string;
  } & MuxStaticRenditionFile>;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  ext?: string;
  name?: string;
  width?: number;
  bitrate?: number;
  filesize?: number;
  height?: number;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = PressItem | MenuItem | RichText | SiteSettings | About | Collection | Project | Release | RichImage | Homepage | Seo | MuxVideo | MuxVideoAsset | MuxAssetData | MuxStaticRenditions | MuxStaticRenditionFile | MuxPlaybackId | MuxTrack | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../web/lib/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage"][0]{    title,    videos[]{      ...,      asset->{        _id,        playbackId,        status,        data      }    },    seo{      title,      description,      image{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }}    }  }
export type HOMEPAGE_QUERYResult = {
  title: string | null;
  videos: Array<{
    _key: string;
    _type: "mux.video";
    asset: {
      _id: string;
      playbackId: string | null;
      status: string | null;
      data: MuxAssetData | null;
    } | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "richImage";
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata: {
          blurHash: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
} | null;
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0]{    richText[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      reference->{        _type,        _id,        title,        slug      }    }  }},    image{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }},    imageText[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      reference->{        _type,        _id,        title,        slug      }    }  }},    seo{      title,      description,      image{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }}    }  }
export type ABOUT_QUERYResult = {
  richText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "externalLink";
      _key: string;
    } | {
      reference: {
        _type: "about";
        _id: string;
        title: string | null;
        slug: null;
      } | {
        _type: "collection";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | {
        _type: "homepage";
        _id: string;
        title: string | null;
        slug: null;
      } | {
        _type: "project";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | {
        _type: "release";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | null;
      _type: "internalLink";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "richImage";
    _key: string;
    markDefs: null;
  }> | null;
  image: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "richImage";
  } | null;
  imageText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "externalLink";
      _key: string;
    } | {
      reference: {
        _type: "about";
        _id: string;
        title: string | null;
        slug: null;
      } | {
        _type: "collection";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | {
        _type: "homepage";
        _id: string;
        title: string | null;
        slug: null;
      } | {
        _type: "project";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | {
        _type: "release";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | null;
      _type: "internalLink";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "richImage";
    _key: string;
    markDefs: null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "richImage";
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata: {
          blurHash: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
} | null;
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    mainMenu[]{      ...{  _key,  label,  linkType,  internalLink->{    _type,    _id,    title,    slug  },  externalLink}    },    footerMenu[]{      ...{  _key,  label,  linkType,  internalLink->{    _type,    _id,    title,    slug  },  externalLink}    },    seo{      title,      description,      image{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }}    }  }
export type SITE_SETTINGS_QUERYResult = {
  mainMenu: Array<{
    _key: string;
    label: string | null;
    linkType: "external" | "internal" | null;
    internalLink: {
      _type: "about";
      _id: string;
      title: string | null;
      slug: null;
    } | {
      _type: "collection";
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | {
      _type: "homepage";
      _id: string;
      title: string | null;
      slug: null;
    } | {
      _type: "project";
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | {
      _type: "release";
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | null;
    externalLink: string | null;
  }> | null;
  footerMenu: Array<{
    _key: string;
    label: string | null;
    linkType: "external" | "internal" | null;
    internalLink: {
      _type: "about";
      _id: string;
      title: string | null;
      slug: null;
    } | {
      _type: "collection";
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | {
      _type: "homepage";
      _id: string;
      title: string | null;
      slug: null;
    } | {
      _type: "project";
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | {
      _type: "release";
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | null;
    externalLink: string | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "richImage";
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata: {
          blurHash: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
} | null;
// Variable: RELEASE_SLUGS_QUERY
// Query: *[_type == "release" && defined(slug.current)]{    "slug": slug.current  }
export type RELEASE_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;
// Variable: RELEASES_QUERY
// Query: *[_type == "release"] | order(release_date desc){    _id,    title,    slug,    release_date,    published,    cover{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }},    coverAlt{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }},    intro,    quote  }
export type RELEASES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  release_date: string | null;
  published: boolean | null;
  cover: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "richImage";
  } | null;
  coverAlt: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "richImage";
  } | null;
  intro: string | null;
  quote: string | null;
}>;
// Variable: RELEASE_BY_SLUG_QUERY
// Query: *[_type == "release" && slug.current == $slug][0]{    _id,    title,    slug,    release_date,    published,    cover{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }},    coverAlt{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }},    intro,    quote,    embed  }
export type RELEASE_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  release_date: string | null;
  published: boolean | null;
  cover: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "richImage";
  } | null;
  coverAlt: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "richImage";
  } | null;
  intro: string | null;
  quote: string | null;
  embed: string | null;
} | null;
// Variable: COLLECTION_SLUGS_QUERY
// Query: *[_type == "collection" && defined(slug.current)]{    "slug": slug.current  }
export type COLLECTION_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;
// Variable: COLLECTIONS_QUERY
// Query: *[_type == "collection"] | order(_createdAt desc){    _id,    title,    slug,    hero{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }},    lines[]{      label,      value,      link    },    intro[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      reference->{        _type,        _id,        title,        slug      }    }  }},    releases[]{      ...,      _type == "reference" => @->{        _id,        title,        slug,        release_date,        published,        cover{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }}      }    },    press[]{      ...{  title,  externalLink,  file{    asset->{      _id,      url,      originalFilename,      size,      mimeType    }  }}    }  }
export type COLLECTIONS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  hero: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "richImage";
  } | null;
  lines: Array<{
    label: string | null;
    value: string | null;
    link: string | null;
  }> | null;
  intro: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "externalLink";
      _key: string;
    } | {
      reference: {
        _type: "about";
        _id: string;
        title: string | null;
        slug: null;
      } | {
        _type: "collection";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | {
        _type: "homepage";
        _id: string;
        title: string | null;
        slug: null;
      } | {
        _type: "project";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | {
        _type: "release";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | null;
      _type: "internalLink";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "richImage";
    _key: string;
    markDefs: null;
  }> | null;
  releases: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    _id: string;
    title: string | null;
    slug: Slug | null;
    release_date: string | null;
    published: boolean | null;
    cover: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata: {
          blurHash: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      caption: string | null;
      _type: "richImage";
    } | null;
  }> | null;
  press: Array<{
    title: string | null;
    externalLink: string | null;
    file: {
      asset: {
        _id: string;
        url: string | null;
        originalFilename: string | null;
        size: number | null;
        mimeType: string | null;
      } | null;
    } | null;
  }> | null;
}>;
// Variable: COLLECTION_BY_SLUG_QUERY
// Query: *[_type == "collection" && slug.current == $slug][0]{    _id,    title,    slug,    hero{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }},    lines[]{      label,      value,      link    },    intro[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      reference->{        _type,        _id,        title,        slug      }    }  }},    seo{      title,      description,      image{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }}    },    releases[]{      ...,      _type == "reference" => @->{        _id,        title,        slug,        release_date,        published,        cover{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }},        coverAlt{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }},        intro,        quote,        embed      }    },    press[]{      ...{  title,  externalLink,  file{    asset->{      _id,      url,      originalFilename,      size,      mimeType    }  }}    }  }
export type COLLECTION_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  hero: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "richImage";
  } | null;
  lines: Array<{
    label: string | null;
    value: string | null;
    link: string | null;
  }> | null;
  intro: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "externalLink";
      _key: string;
    } | {
      reference: {
        _type: "about";
        _id: string;
        title: string | null;
        slug: null;
      } | {
        _type: "collection";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | {
        _type: "homepage";
        _id: string;
        title: string | null;
        slug: null;
      } | {
        _type: "project";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | {
        _type: "release";
        _id: string;
        title: string | null;
        slug: Slug | null;
      } | null;
      _type: "internalLink";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "richImage";
    _key: string;
    markDefs: null;
  }> | null;
  seo: null;
  releases: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    _id: string;
    title: string | null;
    slug: Slug | null;
    release_date: string | null;
    published: boolean | null;
    cover: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata: {
          blurHash: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      caption: string | null;
      _type: "richImage";
    } | null;
    coverAlt: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata: {
          blurHash: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      caption: string | null;
      _type: "richImage";
    } | null;
    intro: string | null;
    quote: string | null;
    embed: string | null;
  }> | null;
  press: Array<{
    title: string | null;
    externalLink: string | null;
    file: {
      asset: {
        _id: string;
        url: string | null;
        originalFilename: string | null;
        size: number | null;
        mimeType: string | null;
      } | null;
    } | null;
  }> | null;
} | null;
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{    "slug": slug.current  }
export type PROJECT_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(_createdAt desc){    _id,    title,    slug,    lines[]{      label,      value,      link    },    columns[]{  _key,  content[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      reference->{        _type,        _id,        title,        slug      }    }  }}},    gallery[]{      ...{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }}    },    images[]{      ...{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }}    },    press[]{      ...{  title,  externalLink,  file{    asset->{      _id,      url,      originalFilename,      size,      mimeType    }  }}    }  }
export type PROJECTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  lines: Array<{
    label: string | null;
    value: string | null;
    link: string | null;
  }> | null;
  columns: Array<{
    _key: string;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h2" | "h3" | "normal";
      listItem?: "bullet" | "number";
      markDefs: Array<{
        href?: string;
        _type: "externalLink";
        _key: string;
      } | {
        reference: {
          _type: "about";
          _id: string;
          title: string | null;
          slug: null;
        } | {
          _type: "collection";
          _id: string;
          title: string | null;
          slug: Slug | null;
        } | {
          _type: "homepage";
          _id: string;
          title: string | null;
          slug: null;
        } | {
          _type: "project";
          _id: string;
          title: string | null;
          slug: Slug | null;
        } | {
          _type: "release";
          _id: string;
          title: string | null;
          slug: Slug | null;
        } | null;
        _type: "internalLink";
        _key: string;
      }> | null;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "richImage";
      _key: string;
      markDefs: null;
    }> | null;
  }> | null;
  gallery: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "richImage";
    _key: string;
  }> | null;
  images: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "richImage";
    _key: string;
  }> | null;
  press: Array<{
    title: string | null;
    externalLink: string | null;
    file: {
      asset: {
        _id: string;
        url: string | null;
        originalFilename: string | null;
        size: number | null;
        mimeType: string | null;
      } | null;
    } | null;
  }> | null;
}>;
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    title,    slug,    lines[]{      label,      value,      link    },    seo{      title,      description,      image{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }}    },    columns[]{  _key,  content[]{  ...,  markDefs[]{    ...,    _type == "internalLink" => {      ...,      reference->{        _type,        _id,        title,        slug      }    }  }}},    gallery[]{      ...{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }}    },    images[]{      ...{  ...,  alt,  caption,  asset->{    ...,    metadata{      blurHash,      dimensions{        width,        height,        aspectRatio      }    }  }}    },    press[]{      ...{  title,  externalLink,  file{    asset->{      _id,      url,      originalFilename,      size,      mimeType    }  }}    }  }
export type PROJECT_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  lines: Array<{
    label: string | null;
    value: string | null;
    link: string | null;
  }> | null;
  seo: null;
  columns: Array<{
    _key: string;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h2" | "h3" | "normal";
      listItem?: "bullet" | "number";
      markDefs: Array<{
        href?: string;
        _type: "externalLink";
        _key: string;
      } | {
        reference: {
          _type: "about";
          _id: string;
          title: string | null;
          slug: null;
        } | {
          _type: "collection";
          _id: string;
          title: string | null;
          slug: Slug | null;
        } | {
          _type: "homepage";
          _id: string;
          title: string | null;
          slug: null;
        } | {
          _type: "project";
          _id: string;
          title: string | null;
          slug: Slug | null;
        } | {
          _type: "release";
          _id: string;
          title: string | null;
          slug: Slug | null;
        } | null;
        _type: "internalLink";
        _key: string;
      }> | null;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "richImage";
      _key: string;
      markDefs: null;
    }> | null;
  }> | null;
  gallery: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "richImage";
    _key: string;
  }> | null;
  images: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: {
        blurHash: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "richImage";
    _key: string;
  }> | null;
  press: Array<{
    title: string | null;
    externalLink: string | null;
    file: {
      asset: {
        _id: string;
        url: string | null;
        originalFilename: string | null;
        size: number | null;
        mimeType: string | null;
      } | null;
    } | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"homepage\"][0]{\n    title,\n    videos[]{\n      ...,\n      asset->{\n        _id,\n        playbackId,\n        status,\n        data\n      }\n    },\n    seo{\n      title,\n      description,\n      image{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n    }\n  }\n": HOMEPAGE_QUERYResult;
    "\n  *[_type == \"about\"][0]{\n    richText[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      reference->{\n        _type,\n        _id,\n        title,\n        slug\n      }\n    }\n  }\n},\n    image{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    imageText[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      reference->{\n        _type,\n        _id,\n        title,\n        slug\n      }\n    }\n  }\n},\n    seo{\n      title,\n      description,\n      image{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n    }\n  }\n": ABOUT_QUERYResult;
    "\n  *[_type == \"siteSettings\"][0]{\n    mainMenu[]{\n      ...{\n  _key,\n  label,\n  linkType,\n  internalLink->{\n    _type,\n    _id,\n    title,\n    slug\n  },\n  externalLink\n}\n    },\n    footerMenu[]{\n      ...{\n  _key,\n  label,\n  linkType,\n  internalLink->{\n    _type,\n    _id,\n    title,\n    slug\n  },\n  externalLink\n}\n    },\n    seo{\n      title,\n      description,\n      image{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n    }\n  }\n": SITE_SETTINGS_QUERYResult;
    "\n  *[_type == \"release\" && defined(slug.current)]{\n    \"slug\": slug.current\n  }\n": RELEASE_SLUGS_QUERYResult;
    "\n  *[_type == \"release\"] | order(release_date desc){\n    _id,\n    title,\n    slug,\n    release_date,\n    published,\n    cover{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    coverAlt{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    intro,\n    quote\n  }\n": RELEASES_QUERYResult;
    "\n  *[_type == \"release\" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    release_date,\n    published,\n    cover{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    coverAlt{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    intro,\n    quote,\n    embed\n  }\n": RELEASE_BY_SLUG_QUERYResult;
    "\n  *[_type == \"collection\" && defined(slug.current)]{\n    \"slug\": slug.current\n  }\n": COLLECTION_SLUGS_QUERYResult;
    "\n  *[_type == \"collection\"] | order(_createdAt desc){\n    _id,\n    title,\n    slug,\n    hero{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    lines[]{\n      label,\n      value,\n      link\n    },\n    intro[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      reference->{\n        _type,\n        _id,\n        title,\n        slug\n      }\n    }\n  }\n},\n    releases[]{\n      ...,\n      _type == \"reference\" => @->{\n        _id,\n        title,\n        slug,\n        release_date,\n        published,\n        cover{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n      }\n    },\n    press[]{\n      ...{\n  title,\n  externalLink,\n  file{\n    asset->{\n      _id,\n      url,\n      originalFilename,\n      size,\n      mimeType\n    }\n  }\n}\n    }\n  }\n": COLLECTIONS_QUERYResult;
    "\n  *[_type == \"collection\" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    hero{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    lines[]{\n      label,\n      value,\n      link\n    },\n    intro[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      reference->{\n        _type,\n        _id,\n        title,\n        slug\n      }\n    }\n  }\n},\n    seo{\n      title,\n      description,\n      image{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n    },\n    releases[]{\n      ...,\n      _type == \"reference\" => @->{\n        _id,\n        title,\n        slug,\n        release_date,\n        published,\n        cover{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n        coverAlt{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n        intro,\n        quote,\n        embed\n      }\n    },\n    press[]{\n      ...{\n  title,\n  externalLink,\n  file{\n    asset->{\n      _id,\n      url,\n      originalFilename,\n      size,\n      mimeType\n    }\n  }\n}\n    }\n  }\n": COLLECTION_BY_SLUG_QUERYResult;
    "\n  *[_type == \"project\" && defined(slug.current)]{\n    \"slug\": slug.current\n  }\n": PROJECT_SLUGS_QUERYResult;
    "\n  *[_type == \"project\"] | order(_createdAt desc){\n    _id,\n    title,\n    slug,\n    lines[]{\n      label,\n      value,\n      link\n    },\n    columns[]{\n  _key,\n  content[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      reference->{\n        _type,\n        _id,\n        title,\n        slug\n      }\n    }\n  }\n}\n},\n    gallery[]{\n      ...{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n    },\n    images[]{\n      ...{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n    },\n    press[]{\n      ...{\n  title,\n  externalLink,\n  file{\n    asset->{\n      _id,\n      url,\n      originalFilename,\n      size,\n      mimeType\n    }\n  }\n}\n    }\n  }\n": PROJECTS_QUERYResult;
    "\n  *[_type == \"project\" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    lines[]{\n      label,\n      value,\n      link\n    },\n    seo{\n      title,\n      description,\n      image{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n    },\n    columns[]{\n  _key,\n  content[]{\n  ...,\n  markDefs[]{\n    ...,\n    _type == \"internalLink\" => {\n      ...,\n      reference->{\n        _type,\n        _id,\n        title,\n        slug\n      }\n    }\n  }\n}\n},\n    gallery[]{\n      ...{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n    },\n    images[]{\n      ...{\n  ...,\n  alt,\n  caption,\n  asset->{\n    ...,\n    metadata{\n      blurHash,\n      dimensions{\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n    },\n    press[]{\n      ...{\n  title,\n  externalLink,\n  file{\n    asset->{\n      _id,\n      url,\n      originalFilename,\n      size,\n      mimeType\n    }\n  }\n}\n    }\n  }\n": PROJECT_BY_SLUG_QUERYResult;
  }
}
